openapi: 3.1.0
info:
  version: 1.0.0
  title: Flower app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of flower app
tags:
  - name: Flower
    description: Flowers delivery.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:4561
  - url: https://example.com/api/v1
paths:
  /shops/shops:
    get:
      $ref: ../src/swagger/paths/shop/allShop.yaml
  /shops/shops/{id}:
    get: 
      $ref: ../src/swagger/paths/shop/getShopById.yaml
  /shops/shops/{shopId}/flowers:
    $ref: ../src/swagger/paths/flower/getFlowerByCurrentShop.yaml
  /shops/orders/{orderId}:
    get: 
      $ref: ../src/swagger/paths/orders/orders.yaml
  /auth/register:
    post: 
      $ref: ../src/swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../src/swagger/paths/auth/login.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
